# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 13:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplenews',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
