# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0002_simplenews_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplenews',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='simplenews',
            old_name='publised',
            new_name='published',
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usager créateur'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='page_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de la page'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien internet'),
        ),
    ]
