# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0003_auto_20180820_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplenews',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='simplenews',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator user name '),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='page_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Page ID Link'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Website Link '),
        ),
    ]
