# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0004_auto_20180821_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplenews',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='simplenews',
            name='document',
        ),
        migrations.RemoveField(
            model_name='simplenews',
            name='page_link',
        ),
        migrations.RemoveField(
            model_name='simplenews',
            name='website_link',
        ),
        migrations.AlterField(
            model_name='simplenews',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
