# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 10:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0005_auto_20190218_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCatNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'News cat',
                'verbose_name_plural': 'News cats',
            },
        ),
    ]
