# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_simple_news', '0007_simplenews_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplenews',
            name='description_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_desc_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image description'),
        ),
    ]
