# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0008_simplenews_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplenews',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='Publication date'),
        ),
    ]
