# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_simple_news', '0009_auto_20190327_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplenews',
            name='description_image',
        ),
    ]
